
name: Lint and type checking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies and linting tools
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy pylint
      - name: Run the tests
        run: |
          mypy . --check-untyped-defs
          pylint ./*.py ./util/*.py
        shell: bash
          